### ISSUE TITLE
TODO Swap out Image_Backend for GregWar

### ISSUE THREAD

**Issue by tractorcow** [tractorcow/silverstripe-framework#16]
See https://github.com/silverstripe/silverstripe-framework/pull/5332#issuecomment-213673115

**Comment by jonom** [comment]
Posted on original PR but here are some other possible contenders FYI:
- [Intervention Image](http://image.intervention.io/) (GD & Imagick support)
- [Imagine](http://imagine.readthedocs.io/en/latest/) (GD, Imagick and Gmagick support)

**Comment by tractorcow** [comment]
Replaced with intervention.
